name: "RST Substitution"
description: "Github action to replace substitutions in rst file."
author: "junghoon-vans"
inputs:
  input-file:
    description: "The file path to read contents."
    required: false
  output-file:
    description: "The file path to write contents."
    required: false
  substitutions:
    description: "A key-value of substitutions."
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - run: python -m pip install varst
      shell: bash
    - run: |
        cmd="varst"

        if [ -n "${{ inputs.input-file }}" ]; then
          cmd+=" -i ${{ inputs.input-file }}"
        fi

        if [ -n "${{ inputs.output-file }}" ]; then
          cmd+=" -o ${{ inputs.output-file }}"
        fi

        eval "${cmd} ${{ inputs.substitutions }}"
      shell: bash
branding:
  icon: "repeat"
  color: "gray-dark"